import { SiteContent } from "./types";
const en: SiteContent = {
  locale: "en",
  nav: { links: [{label:"projects",id:"proyectos"},{label:"about",id:"por-que-nosotros"}], contact:{label:"contact",id:"contacto"} },
  hero: { prefix:"latroupe", rotatingWords:["designs","technifies","organises","improves","optimises","executes","builds","anticipates"], suffix:"behind the scenes", description:"We expand the capabilities of architecture and interior design studios supporting them throughout every phase of a project." },
  about: { eyebrow:"Really...", headline:"There are few things we cannot do", blocks:["Those who work with latroupe rely on us to expand their teams without compromising on quality.","We support design, planning, technical development, and project management, whenever needed. We integrate in a coordinated way with the team, adapting to their way of working, whatever it may be.","We have the experience and capability to work on all types of projects, regardless of their magnitude and complexity."] },
  projectsSection: { headline:"A selection of recent projects in which we collaborate" },
  projects: [
    { id:"al-ameen", title:"Al Ameen |\nCorporate Offices", location:"Jeddah, KSA", thumbnail:"/images/projects/al-ameen/hero.jpg", type:"Corporate Offices / Workplace", client:"confidential", partner:"BDG", phase:"Stage 3 – Technical Development", status:"Project completed", inDevelopment:false, heroImage:"/images/projects/al-ameen/hero.jpg", shortDesc:"Technical development and BIM coordination for a corporate project in Saudi Arabia.", longDesc:["For the Al Ameen corporate offices project in Jeddah, we joined as BIM support and technical production team during Stage 3.","The main challenge was ensuring technical precision and document consistency in an international environment.","The project was developed in a collaborative BIM environment, centralized in Autodesk Construction Cloud (ACC)."], laborTitle:"Our scope of work included:", labor:["Production and development of Revit models according to project standards.","Generation of technical drawing packages for Stage 3 delivery.","Coordination with architecture, MEP, and other discipline teams.","Clash detection and resolution.","Implementation of document quality control processes (QA/QC).","Continuous support to the design team on adjustments and technical refinements."], closingText:"We ensured consistent technical documentation aligned with client and consultant requirements.", closingText2:"The key differentiator was our ability to bring structure, BIM rigor, and specialized technical reinforcement at a critical project phase.", images:[{src:"/images/projects/al-ameen/render-lobby.jpg",caption:"Lobby render"},{src:"/images/projects/al-ameen/render-main.png",caption:"Lattice view"},{src:"/images/projects/al-ameen/floor-plan.png",caption:"Ground floor double height"},{src:"/images/projects/al-ameen/exploded.png",caption:"Ground floor exploded view"},{src:"/images/projects/al-ameen/moodboard.png",caption:"Moodboard"}] },
    { id:"rochester-row", title:"Rochester Row |\nOffice Refurbishment", location:"London, UK", thumbnail:"/images/projects/rochester-row/hero.jpg", type:"Offices / Workplace", status:"Project completed", inDevelopment:false, heroImage:"/images/projects/rochester-row/hero.jpg", shortDesc:"Office refurbishment in central London.", longDesc:["Project information coming soon."], labor:[], images:[] },
    { id:"oro-hato-rey", title:"ORO Hato Rey |\nHotel Renovation", location:"San Juan, Puerto Rico", thumbnail:"/images/projects/oro-hato-rey/hero.jpg", type:"Hotel / Hospitality", status:"In progress", inDevelopment:false, heroImage:"/images/projects/oro-hato-rey/hero.jpg", shortDesc:"Full renovation of a boutique hotel in San Juan.", longDesc:["Project information coming soon."], labor:[], images:[] },
    { id:"sant-feliu", title:"Sant Feliu de Guíxols |\nResidential Renovation", location:"Girona, Spain", thumbnail:"/images/projects/sant-feliu/hero.jpg", type:"Residential", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/sant-feliu/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"holbein-gardens", title:"Holbein Gardens |\nCorporate Offices", location:"London, UK", thumbnail:"/images/projects/holbein-gardens/hero.jpg", type:"Offices / Workplace", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/holbein-gardens/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"andaz-turks", title:"Andaz Turks & Caicos at Grace Bay |\nHotel Renovation", location:"Turks and Caicos Islands", thumbnail:"/images/projects/andaz-turks/hero.jpg", type:"Hotel", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/andaz-turks/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
  ],
  trust: { headline:"Trusted by:", logos:[{name:"Accor",src:"/images/logos/blanco/accor-blanco.svg"},{name:"Aena",src:"/images/logos/blanco/aena-blanco.svg"},{name:"Airia",src:"/images/logos/blanco/airia-blanco.svg"},{name:"Amazon",src:"/images/logos/blanco/amazon-blanco.svg"},{name:"BDG",src:"/images/logos/blanco/bdg-blanco.svg"},{name:"BGY",src:"/images/logos/blanco/bgy-blanco.svg"},{name:"Hyatt",src:"/images/logos/blanco/hyatt-blanco.svg"},{name:"Joan Lao",src:"/images/logos/blanco/joan-lao-blanco.svg"},{name:"LEGO",src:"/images/logos/blanco/lego-blanco.svg"},{name:"M Gallery",src:"/images/logos/blanco/m-gallery-blanco.svg"},{name:"Marriott",src:"/images/logos/blanco/marriott-blanco.svg"},{name:"Modus Operandi",src:"/images/logos/blanco/modus-operandi-blanco.svg"}] },
  methodology: {
    headline:"Experience defines our methodology",
    intro:"Our goal has always been simple: to be genuinely useful to the teams we work with.",
    subtitle:"This shapes how latroupe operates:",
    pillars:[
      {number:"I)",title:"The system adapts to the project,",subtitle:"(not the other way around)",paragraphs:["Well-constructed processes influence both the collaborating teams and the quality of the result.","Our system is flexible and proactive allowing us to work autonomously, without needing constant supervision."]},
      {number:"II)",title:"A hybrid model",subtitle:"(and global talent)",paragraphs:["Our multidisciplinary experience allows us to anticipate project needs and bring in the right talent for each case."]},
      {number:"III)",title:"We solve",subtitle:"(with intention)",paragraphs:["Being aware of our role, we provide more than just extra help.","At latroupe, we actively contribute ideas and solutions, based on our experience, to enrich from within."]},
    ],
  },
  whyUs: { headline:"Why us?", paragraphs:["At latroupe, we've worked across architecture, construction, design, technology, and business.","That is why we can offer a service that adapts to your current needs—and evolves as they change.","Our way of working is simple (but not simplistic) and is based on establishing sustainable, long-term relationships.","If you think we can help, it all starts with a conversation."] },
  contact: { headline:"Let's start a project together", fields:{name:"Name",email:"Email",company:"Message",message:"Write us a message",submit:"Send",sending:"Sending...",sent:"Sent!",error:"Could not send. Please try again."}, legal:"By clicking Send, you accept our data protection policy and agree that we may contact you.", legalLinkPhrase:"data protection policy", legalLinkHref:"/en/legal-notice" },
  footer: { links:[{label:"Privacy",href:"/en/privacy"},{label:"Cookies",href:"/en/cookies"},{label:"Legal notice",href:"/en/legal-notice"}], social:[{label:"Linkedin",href:"https://www.linkedin.com/company/latroupestudio/"},{label:"Instagram",href:"https://www.instagram.com/latroupestudio"},{label:"Pinterest",href:"https://www.pinterest.es/latroupestudio/"}], workWithUs:{label:"Work with us",href:"https://invented-cactus-ce6.notion.site/Trabajar-en-LaTroupe-cd9c990923954418bd2e6a3df58b2500"}, copyright:"Developed by latroupe ( ) 2026 © All rights reserved.", legal:"" },
  cookieBanner: {
    message: "We use first-party and third-party cookies to analyze site usage and improve our services. Non-essential cookies are only installed with your consent.",
    moreInfo: "Learn more",
    accept: "Accept",
    reject: "Reject",
  },
  overlay: { close:"CLOSE", inDevelopment:"Ongoing", comingSoon:"Coming soon" },
  bim: {
    meta: {
      title: "BIM Consulting & Modelling Services UK | latroupe()",
      description: "BIM consulting, modelling and management services across the UK. ISO 19650 & COBie-ready, delivered to your standards and your timeline. Book a consultation.",
    },
    nav: {
      links: [{ label: "services", id: "services" }, { label: "case study", id: "case-study" }],
      contact: { label: "let's talk", id: "contacto" },
      home: { label: "latroupe", id: "/en" },
    },
    hero: {
      h1: "BIM Consulting & Modelling Services",
      subhead: "Coordinated, data-rich BIM — delivered to your standards, and to your timeline. We plug into your team at any project stage and keep you in control of your information from day one.",
      cta: { label: "book a consultation", id: "contacto" },
      ctaSub: "Tell us about your project, we'll reply within one working day.",
    },
    trustBand: {
      eyebrow: "trusted by leading studios and brands",
      tagline: "BIM delivered across the UK, Europe and beyond — for studios, contractors and developers.",
    },
    services: {
      eyebrow: "our bim services",
      headline: "End-to-end BIM services",
      sub: "Pick the ones you need, or let us run the lot.",
      items: [
        { number:"I)", title:"BIM Modelling", subtitle:"(revit)", paragraphs:["Accurate, data-rich Revit models built to your required level of detail (LOD 200–500). Architectural, structural and MEP BIM services, fully coordinated and ready for delivery."] },
        { number:"II)", title:"BIM Content Creation", subtitle:"(families & templates)", paragraphs:["Custom Revit families, templates and standards libraries — so your models stay consistent and reusable across every project."] },
        { number:"III)", title:"BIM Management & Information Management", subtitle:"(information delivery)", paragraphs:["A dedicated BIM manager to lead your information delivery — setting up the CDE, naming, and standards so your data stays clean, ordered and auditable."] },
        { number:"IV)", title:"BIM Execution Plan", subtitle:"(bep)", paragraphs:["We write and maintain your BIM Execution Plan so the whole team works to one agreed method — aligned with the UK BIM Framework from the start."] },
        { number:"V)", title:"BIM Coordination & Clash Detection", subtitle:"(multidisciplinary)", paragraphs:["Multidiscipline coordination that catches clashes before they reach site."] },
        { number:"VI)", title:"Embedded BIM Support", subtitle:"(your team, extended)", paragraphs:["Senior BIM consultants and Revit specialists who work as part of your studio for the length of a project — a true extension of your team, not a faceless production line."] },
        { number:"VII)", title:"BIM Project & Data Management Consultancy", subtitle:"(data & digital twin)", paragraphs:["From BIM project management consultancy to BIM data management consultancy and digital twin foundations — we keep the information layer of your project under control."] },
      ],
    },
    deliverables: {
      eyebrow: "what you get",
      headline: "Clear deliverables, agreed up front",
      sub: "You always know exactly what lands.",
      items: [
        { number:"01", title:"Coordinated Revit models", text:"to your chosen LOD (200 / 300 / 400 / 500)" },
        { number:"02", title:"Construction & GA drawings", text:"plans, sections, schematics and risers" },
        { number:"03", title:"Clash & coordination reports", text:"issues found, tracked and resolved" },
        { number:"04", title:"BOQ / quantities", text:"schedules pulled straight from the model" },
        { number:"05", title:"COBie data drops", text:"structured asset data for handover, aligned to your BEP" },
        { number:"06", title:"QA reports", text:"every model checked before it reaches you" },
      ],
    },
    adapts: {
      headline: "We adapt to you",
      sub: "Most providers make you fit their process. We do the opposite.",
      items: [
        { title:"We work in your hours.", text:"Real overlap with your working day — not a model that lands in your inbox overnight with no one to ask." },
        { title:"We join your team.", text:"We plug into your CDE, your naming, your workflow. You don't change how you work; we adapt to it." },
        { title:"We start from whatever you have.", text:"2D PDFs, CAD, an existing Revit model, markups or specs — we work from your inputs, in your formats." },
        { title:"You stay in control of your information.", text:"At every stage you can see exactly what's modelled, what's pending and where the data lives. No black boxes." },
      ],
    },
    riba: {
      eyebrow: "support at any riba stage",
      headline: "Whatever stage your project is at, we plug in.",
      caption: "Come to us at the start or pick us up mid-project — from BEP and standards, through modelling and coordination, to COBie-ready handover.",
      stages: [
        { number:"0", label:"Strategic Definition" },
        { number:"1", label:"Preparation & Briefing" },
        { number:"2", label:"Concept Design" },
        { number:"3", label:"Spatial Coordination" },
        { number:"4", label:"Technical Design" },
        { number:"5", label:"Manufacturing & Construction" },
        { number:"6", label:"Handover" },
        { number:"7", label:"Use" },
      ],
    },
    standards: {
      eyebrow: "standards & quality, in plain terms",
      headline: "Compliance shouldn't feel like an exam.",
      sub: "We handle the standards so you don't have to memorise them.",
      items: [
        { code:"ISO 19650", description:"The international standard for managing information across a project's life cycle." },
        { code:"COBie", description:"Structured asset data your client can actually use after handover." },
        { code:"UK BIM Framework / PAS 1192", description:"The UK way of working, built into how we run every job." },
      ],
    },
    sectors: {
      eyebrow: "sectors we work in",
      headline: "Generalist by design. We deliver BIM across:",
      items: ["Residential","Commercial & offices","Hospitality","Retail","Mixed-use","Education","Airports & aviation","Data centres","Interiors & fit-out"],
      sub: "If it gets designed, built and operated, we can model and manage it.",
    },
    why: {
      eyebrow: "why latroupe()",
      headline: "Clarity and control — from the first model to handover.",
      items: [
        { title:"Clarity and control.", text:"You always know what's done, what's next and where your data is." },
        { title:"We adapt to your team.", text:"Your hours, your workflow, your standards." },
        { title:"Multi-standard, not single-track.", text:"ISO 19650, COBie and the UK BIM Framework are day-to-day for us, not a learning curve." },
      ],
    },
    tools: {
      eyebrow: "built in-house",
      headline: "We build our own tools",
      sub: "We don't just deliver models — we build software to keep BIM data clean and ordered. It's how we guarantee the rigour behind every project we hand over.",
      items: [
        { name:"specto", description:"model & data inspection", img:"/images/bim-consultancy/tools/specto.png" },
        { name:"modelcleaner", description:"clean, ordered bim data", img:"/images/bim-consultancy/tools/modelcleaner.png" },
        { name:"pdf comparator", description:"drawing revision compare", img:"/images/bim-consultancy/tools/pdfcomparator.svg" },
      ],
    },
    caseStudy: {
      eyebrow: "case study",
      headline: "LEGO London Hub",
      heroImage: "/images/case-studies/lego-london-hub/hero.jpg",
      location: "London, UK",
      year: "2026",
      area: "20,000 sqm",
      typology: "Workplace",
      author: "BDG architecture + design",
      endClient: "LEGO",
      intro: "latroupe() joined BDG at Stage 2 as its BIM management and production partner for the LEGO London Hub fit-out. We set up and ran the project's entire BIM information environment and then delivered the Stage 3 model and full drawing package — all inside BDG's secured platforms. The challenge was to stand up a fully ISO 19650-compliant information environment from scratch, align to BDG's in-house BIM 7AA standard, coordinate multiple parties and consultants within a controlled corporate IT environment, and produce a large, multi-package Stage 3 drawing set at pace with full traceability.",
      standards: "ISO 19650 · BDG BIM 7AA standard · CDE (Dalux + Autodesk Construction Cloud) · IFC exchange · RIBA Plan of Work 2020 · UK Building Regulations",
      whatWeDid: [
        { title:"BIM & information management", items:[
          "Authored and maintained the BIM Execution Plan (including a Revit-to-Dalux guide), reviewed the EIR and produced the MIDP, BDG TIDP, Information Responsibility Matrix and risk register.",
          "Set up the CDE end-to-end: Dalux setup and plug-ins, model structure diagram, levels & grids model, model-splitting strategy, IFC export/upload and ACC access & permissions management.",
          "Ran BIM coordination meetings, clash-detection tests and successive model uploads (Dalux v01–v04 and Stage 3+), plus BDG model reviews and audits (worksets, FF&E splash page, catering model to BDG ACC).",
          "Wrote the BIM text and appendices for the Stage 3 report.",
        ]},
        { title:"BIM modelling & drawing production", items:[
          "Planning & existing plans",
          "Proposed GA; partitions (AV back-to-back meeting rooms, teapoint bulkheads, conference-room walls); raised-access-floor plans; floor finishes",
          "Elevations; proposed sections",
          "Joinery, stairs / working platform",
          "Detail drawings",
          "Doors and fire strategy; AV modelling",
        ]},
      ],
      result: "A fully governed, ISO 19650-compliant BIM environment and a comprehensive, coordinated Stage 3 model and drawing set — delivered continuously inside BDG's platforms and standards, with latroupe() acting as BDG's embedded BIM management and production team.",
      imageCredit: "Image © LEGO",
    },
    faq: {
      eyebrow: "faq",
      headline: "FAQs",
      items: [
        { question:"Can you join a project that's already underway?", answer:"Yes. We regularly pick projects up mid-stage — we audit what already exists, set up or clean the information environment, and carry on from there without disrupting your delivery." },
        { question:"How do we get started?", answer:"A short call to understand the project and its stage. We then propose the scope, standards and deliverables — and agree them — before the collaboration begins." },
        { question:"Fixed fee or by stage?", answer:"Both. We scope by stage or by deliverable, and agree the commercial model that fits how you run the project." },
        { question:"Can you provide extra BIM capacity for our team?", answer:"Yes. We can embed senior BIM consultants and Revit specialists in your studio for the length of a project, working as part of your team." },
        { question:"Can you work inside our own platforms and standards?", answer:"Yes. We routinely deliver entirely inside our clients' secured platforms and to their in-house BIM standards, working as part of their environment rather than imposing ours." },
        { question:"What is a BIM Execution Plan (BEP)?", answer:"A document that sets out how BIM will be delivered on your project — roles, standards, software, LOD and data drops — so the whole team works one way. We write and maintain it for you." },
        { question:"What does a BIM manager do?", answer:"A BIM manager leads your information delivery — setting standards, running the CDE and keeping data quality high across every discipline. We can provide one for your project." },
        { question:"Which software do you use?", answer:"Revit is our main modelling platform, but we also work in ArchiCAD and with tools like Dalux and other common BIM platforms. If you have a specific requirement, tell us — chances are we can help." },
        { question:"Do you deliver COBie and structured asset data?", answer:"Yes. We hand over COBie-ready, structured data your client can actually use to operate the building after handover." },
      ],
    },
    header: {
      popup: {
        whoLabel: "( who are you? )",
        namePlaceholder: "Your name",
        reachLabel: "( how do we reach you? )",
        emailPlaceholder: "Your email",
        projectLabel: "( what's the project? )",
        projectPlaceholder: "Type, stage, location",
        moreLabel: "( tell us more )",
        morePlaceholder: "A short description of what you need",
        submit: "Send",
        legal: "By submitting this form you agree to our privacy policy.",
        legalLinkPhrase: "privacy policy",
        legalLinkHref: "/en/privacy",
        closeAriaLabel: "Close",
      },
    },
    ctaSection: {
      headline: "Let's talk.",
      sub: "Tell us where your project is — start, mid-stage or already on site. We'll map the BIM support you need, to your standards and your timeline. No obligation, and we reply within one working day.",
      fields: {
        whoLabel: "( who are you? )",
        namePlaceholder: "Your name",
        reachLabel: "( how do we reach you? )",
        emailPlaceholder: "Your email",
        projectLabel: "( what's the project? )",
        projectPlaceholder: "Type, stage, location",
        moreLabel: "( tell us more )",
        morePlaceholder: "A short description of what you need",
        submit: "Send",
        sending: "Sending...",
        sent: "Sent!",
        error: "Could not send. Please try again.",
      },
      legal: "By submitting this form you agree to our privacy policy. We only use your details to reply to your enquiry — never for anything else.",
      legalLinkPhrase: "privacy policy",
      legalLinkHref: "/en/privacy",
    },
  },
};
export default en;
