import { SiteContent } from "./types";
const en: SiteContent = {
  locale: "en",
  nav: { links: [{label:"projects",id:"proyectos"},{label:"about",id:"por-que-nosotros"}], contact:{label:"contact",id:"contacto"} },
  hero: { prefix:"latroupe", rotatingWords:["designs","technifies","organises","improves","optimises","executes","builds","anticipates"], suffix:"behind the scenes", description:"We expand the capabilities of architecture and interior design studios supporting them throughout every phase of a project." },
  about: { eyebrow:"Really...", headline:"There are few things we cannot do", blocks:["Those who work with latroupe rely on us to expand their teams without compromising on quality.","We support design, planning, technical development, and project management, whenever needed. We integrate in a coordinated way with the team, adapting to their way of working, whatever it may be.","We have the experience and capability to work on all types of projects, regardless of their magnitude and complexity."] },
  projectsSection: { headline:"A selection of recent projects in which we collaborate" },
  projectsCollage: [
    { id:"rochester-row", title:"Rochester Row", location:"London, UK", image:"/images/projects/collage/s01-hero.jpg" },
    { id:"oro-hato-rey", title:"Oro Hato Rey Marriott Autograph Collection", location:"San Juan, Puerto Rico", image:"/images/projects/collage/ororender.jpg" },
    { id:"al-ameen", title:"Al Ameen HQ", location:"Jeddah, Saudi Arabia", image:"/images/projects/collage/vista-celosia-sm.jpg" },
    { id:"sant-feliu", title:"Sant Feliu", location:"Barcelona, Spain", image:"/images/projects/collage/dorm.jpg" },
    { id:"andaz-turks", title:"Andaz Turks and Caicos", location:"Grace Bay, Turks and Caicos", image:"/images/projects/collage/vista-celosia-2.jpg" },
    { id:"holbein-gardens", title:"Holbein Gardens", location:"London, UK", image:"/images/projects/collage/vista-celosia-3.jpg" },
    { id:"workplace-competition", title:"Workplace Competition", location:"London, UK", image:"/images/projects/collage/workplace-open.png" },
    { id:"llavaneres", title:"Llavaneres", location:"Barcelona, Spain", image:"/images/projects/collage/llavaneres-salon.jpg" },
    { id:"lego-london-hub", title:"LEGO London HUB", location:"London, UK", image:"/images/projects/collage/lego-southbank.jpg" },
    { id:"amazon-aws-hq", title:"Amazon (AWS) HQ", location:"Abu Dhabi, UAE", image:"/images/projects/collage/amazon-aws-hq.png" },
    { id:"aena-east-lot", title:"Aena East Lot Airports", location:"Spain", image:"/images/projects/collage/aena-east-lot.jpg" },
  ],
  projects: [
    { id:"al-ameen", title:"Al Ameen |\nCorporate Offices", location:"Jeddah, KSA", thumbnail:"/images/projects/al-ameen/hero.jpg", type:"Corporate Offices / Workplace", client:"confidential", partner:"BDG", phase:"Stage 3 – Technical Development", status:"Project completed", inDevelopment:false, heroImage:"/images/projects/al-ameen/hero.jpg", shortDesc:"Technical development and BIM coordination for a corporate project in Saudi Arabia.", longDesc:["For the Al Ameen corporate offices project in Jeddah, we joined as BIM support and technical production team during Stage 3.","The main challenge was ensuring technical precision and document consistency in an international environment.","The project was developed in a collaborative BIM environment, centralized in Autodesk Construction Cloud (ACC)."], laborTitle:"Our scope of work included:", labor:["Production and development of Revit models according to project standards.","Generation of technical drawing packages for Stage 3 delivery.","Coordination with architecture, MEP, and other discipline teams.","Clash detection and resolution.","Implementation of document quality control processes (QA/QC).","Continuous support to the design team on adjustments and technical refinements."], closingText:"We ensured consistent technical documentation aligned with client and consultant requirements.", closingText2:"The key differentiator was our ability to bring structure, BIM rigor, and specialized technical reinforcement at a critical project phase.", images:[{src:"/images/projects/al-ameen/render-lobby.jpg",caption:"Lobby render"},{src:"/images/projects/al-ameen/render-main.png",caption:"Lattice view"},{src:"/images/projects/al-ameen/floor-plan.png",caption:"Ground floor double height"},{src:"/images/projects/al-ameen/exploded.png",caption:"Ground floor exploded view"},{src:"/images/projects/al-ameen/moodboard.png",caption:"Moodboard"}] },
    { id:"rochester-row", title:"Rochester Row |\nOffice Refurbishment", location:"London, UK", thumbnail:"/images/projects/rochester-row/hero.jpg", type:"Offices / Workplace", status:"Project completed", inDevelopment:false, heroImage:"/images/projects/rochester-row/hero.jpg", shortDesc:"Office refurbishment in central London.", longDesc:["Project information coming soon."], labor:[], images:[] },
    { id:"oro-hato-rey", title:"ORO Hato Rey |\nHotel Renovation", location:"San Juan, Puerto Rico", thumbnail:"/images/projects/oro-hato-rey/hero.jpg", type:"Hotel / Hospitality", status:"In progress", inDevelopment:false, heroImage:"/images/projects/oro-hato-rey/hero.jpg", shortDesc:"Full renovation of a boutique hotel in San Juan.", longDesc:["Project information coming soon."], labor:[], images:[] },
    { id:"sant-feliu", title:"Sant Feliu de Guíxols |\nResidential Renovation", location:"Girona, Spain", thumbnail:"/images/projects/sant-feliu/hero.jpg", type:"Residential", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/sant-feliu/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"holbein-gardens", title:"Holbein Gardens |\nCorporate Offices", location:"London, UK", thumbnail:"/images/projects/holbein-gardens/hero.jpg", type:"Offices / Workplace", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/holbein-gardens/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"andaz-turks", title:"Andaz Turks & Caicos at Grace Bay |\nHotel Renovation", location:"Turks and Caicos Islands", thumbnail:"/images/projects/andaz-turks/hero.jpg", type:"Hotel", status:"Ongoing", inDevelopment:true, heroImage:"/images/projects/andaz-turks/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
  ],
  trust: { headline:"they trust latroupe", logos:[{name:"Joan Lao",src:"/images/logos/joan-lao.svg"},{name:"Hyatt",src:"/images/logos/hyatt.svg"},{name:"Amazon",src:"/images/logos/amazon.svg"},{name:"Aena",src:"/images/logos/aena.svg"},{name:"LEGO",src:"/images/logos/lego.svg"},{name:"BDG",src:"/images/logos/bdg.svg"},{name:"Marriott",src:"/images/logos/marriott.svg"},{name:"M Gallery",src:"/images/logos/m-gallery.svg"},{name:"Accor",src:"/images/logos/accor.svg"},{name:"Modus Operandi",src:"/images/logos/modus-operandi.svg"},{name:"Radisson Hotels",src:"/images/logos/radisson.svg"},{name:"Airia",src:"/images/logos/airia.svg"},{name:"BGY",src:"/images/logos/bgy.svg"}] },
  methodology: {
    headline:"Experience defines our methodology",
    intro:"Our goal has always been simple: to be genuinely useful to the teams we work with.",
    subtitle:"This shapes how latroupe operates:",
    pillars:[
      {number:"I)",title:"The system adapts to the project,",subtitle:"(not the other way around)",paragraphs:["Well-constructed processes influence both the collaborating teams and the quality of the result.","Our system is flexible and proactive allowing us to work autonomously, without needing constant supervision."]},
      {number:"II)",title:"A hybrid model",subtitle:"(and global talent)",paragraphs:["Our multidisciplinary experience allows us to anticipate project needs and bring in the right talent for each case."]},
      {number:"III)",title:"We solve",subtitle:"(with intention)",paragraphs:["Being aware of our role, we provide more than just extra help.","At latroupe, we actively contribute ideas and solutions, based on our experience, to enrich from within."]},
    ],
  },
  whyUs: { headline:"Why us?", paragraphs:["At latroupe, we've worked across architecture, construction, design, technology, and business.","That is why we can offer a service that adapts to your current needs—and evolves as they change.","Our way of working is simple (but not simplistic) and is based on establishing sustainable, long-term relationships.","If you think we can help, it all starts with a conversation."] },
  contact: {
    headline:"Let's talk.",
    intro:"Tell us where your project is — at the start, mid-stage or already on site. It all begins with a video call to get to know each other. No commitment: we reply within one working day.",
    fields:{
      name:"( who are you? )", email:"( how do we reach you? )", company:"( tell us more )",
      namePlaceholder:"Your name", emailPlaceholder:"Your email", message:"A short description of what you need",
      submit:"Send", sending:"Sending...", sent:"Sent!", error:"Could not send. Please try again.",
    },
    legal:"By submitting this form you agree to our privacy policy. We only use your details to reply to your enquiry — never for anything else.",
    legalLinkPhrase:"privacy policy",
    legalLinkHref:"/en/privacy",
  },
  footer: { links:[{label:"Privacy",href:"/en/privacy"},{label:"Cookies",href:"/en/cookies"},{label:"Legal notice",href:"/en/legal-notice"}], social:[{label:"Linkedin",href:"https://www.linkedin.com/company/latroupestudio/"},{label:"Instagram",href:"https://www.instagram.com/latroupestudio"},{label:"Pinterest",href:"https://www.pinterest.es/latroupestudio/"}], workWithUs:{label:"Work with us",href:"https://invented-cactus-ce6.notion.site/Trabajar-en-LaTroupe-cd9c990923954418bd2e6a3df58b2500"}, copyright:"Developed by latroupe ( ) 2026 © All rights reserved.", legal:"" },
  cookieBanner: {
    message: "We use first-party and third-party cookies to analyze site usage and improve our services. Non-essential cookies are only installed with your consent.",
    moreInfo: "Learn more",
    accept: "Accept",
    reject: "Reject",
  },
  overlay: { close:"CLOSE", inDevelopment:"Ongoing", comingSoon:"Coming soon" },
};
export default en;
