import { SiteContent } from "./types";
const es: SiteContent = {
  locale: "es",
  nav: { links: [{ label: "proyectos", id: "proyectos" },{ label: "nosotros", id: "por-que-nosotros" }], contact: { label: "contacto", id: "contacto" } },
  hero: {
    prefix: "latroupe",
    rotatingWords: ["diseña","tecnifica","ordena","mejora","optimiza","ejecuta","construye","anticipa"],
    suffix: "contigo",
    description: "Reforzamos la capacidad de los estudios de arquitectura o interiorismo y les acompañamos en todas las fases de desarrollo de cada proyecto.",
  },
  about: {
    eyebrow: "Realmente...",
    headline: "Hay pocas cosas que no podamos hacer",
    blocks: [
      "Quienes nos eligen saben que con latroupe pueden ampliar el equipo interno manteniendo un nivel de calidad excelente en su trabajo.",
      "Estamos para diseñar, proyectar, tecnificar, gestionar o brindar cualquier apoyo cuando se necesite. Nos integramos de forma coordinada con el equipo adaptándonos a su forma de trabajar, sea cual sea.",
      "Tenemos la experiencia y la capacidad de colaborar en proyectos de todo tipo, sin importar la magnitud ni la complejidad.",
    ],
  },
  projectsSection: { headline: "Una selección de proyectos recientes en los que colaboramos" },
  projects: [
    { id:"al-ameen", title:"Al Ameen |\nOficinas corporativas", location:"Jeddah, KSA", thumbnail:"/images/projects/al-ameen/hero.jpg", type:"Oficinas corporativas / Workplace", client:"confidencial", partner:"BDG", phase:"Stage 3 – Desarrollo técnico", status:"Proyecto completado", inDevelopment:false, heroImage:"/images/projects/al-ameen/hero.jpg", shortDesc:"Desarrollo técnico y coordinación BIM para proyecto corporativo en Arabia Saudí.", longDesc:["Para el proyecto de oficinas corporativas Al Ameen en Jeddah, nos incorporamos como equipo de soporte BIM y producción técnica durante Stage 3.","El reto principal fue garantizar precisión técnica y coherencia documental en un entorno internacional.","El proyecto se desarrolló en entorno colaborativo BIM, centralizado en Autodesk Construction Cloud (ACC)."], laborTitle:"Nuestra labor incluyó:", labor:["Producción y desarrollo de modelos en Revit conforme a los estándares del proyecto.","Generación de paquetes de planos técnicos para entrega en Stage 3.","Coordinación con equipos de arquitectura, MEP y resto de disciplinas.","Revisión y resolución de interferencias.","Implementación de procesos de control de calidad documental (QA/QC).","Soporte continuo al equipo de diseño en ajustes y reducciones técnicas."], closingText:"Se aseguró una documentación técnica consistente y alineada con los requerimientos del cliente.", closingText2:"El valor diferencial fue la capacidad de aportar estructura, rigor BIM y refuerzo técnico especializado.", images:[{src:"/images/projects/al-ameen/render-lobby.jpg",caption:"Render del lobby"},{src:"/images/projects/al-ameen/render-main.png",caption:"Escalonado de celosía"},{src:"/images/projects/al-ameen/floor-plan.png",caption:"Doble nivel de planta baja"},{src:"/images/projects/al-ameen/exploded.png",caption:"Explotado planta baja"},{src:"/images/projects/al-ameen/moodboard.png",caption:"Moodboard"}] },
    { id:"rochester-row", title:"Rochester Row |\nReforma de oficinas", location:"Londres, Reino Unido", thumbnail:"/images/projects/rochester-row/hero.jpg", type:"Oficinas / Workplace", status:"Proyecto completado", inDevelopment:false, heroImage:"/images/projects/rochester-row/hero.jpg", shortDesc:"Refurbishment de oficinas en el centro de Londres.", longDesc:["Información del proyecto próximamente."], labor:[], images:[] },
    { id:"oro-hato-rey", title:"ORO Hato Rey |\nRenovación de hotel", location:"San Juan, Puerto Rico", thumbnail:"/images/projects/oro-hato-rey/hero.jpg", type:"Hotel / Hospitality", status:"En desarrollo", inDevelopment:false, heroImage:"/images/projects/oro-hato-rey/hero.jpg", shortDesc:"Renovación integral de hotel boutique en San Juan.", longDesc:["Información del proyecto próximamente."], labor:[], images:[] },
    { id:"sant-feliu", title:"Sant Feliu de Guíxols |\nRenovación residencial", location:"Girona, Spain", thumbnail:"/images/projects/sant-feliu/hero.jpg", type:"Residencial", status:"En desarrollo", inDevelopment:true, heroImage:"/images/projects/sant-feliu/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"holbein-gardens", title:"Holbein Gardens |\nOficinas corporativas", location:"Londres, Reino Unido", thumbnail:"/images/projects/holbein-gardens/hero.jpg", type:"Oficinas / Workplace", status:"En desarrollo", inDevelopment:true, heroImage:"/images/projects/holbein-gardens/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
    { id:"andaz-turks", title:"Andaz Turks & Caicos at Grace Bay |\nRenovación de hotel", location:"Turks and Caicos Islands", thumbnail:"/images/projects/andaz-turks/hero.jpg", type:"Hotel", status:"En desarrollo", inDevelopment:true, heroImage:"/images/projects/andaz-turks/hero.jpg", shortDesc:"", longDesc:[], labor:[], images:[] },
  ],
  trust: { headline: "Confían en latroupe:", logos: [
    {name:"Accor",src:"/images/logos/blanco/accor-blanco.svg"},{name:"Aena",src:"/images/logos/blanco/aena-blanco.svg"},{name:"Airia",src:"/images/logos/blanco/airia-blanco.svg"},{name:"Amazon",src:"/images/logos/blanco/amazon-blanco.svg"},{name:"BDG",src:"/images/logos/blanco/bdg-blanco.svg"},{name:"BGY",src:"/images/logos/blanco/bgy-blanco.svg"},{name:"Hyatt",src:"/images/logos/blanco/hyatt-blanco.svg"},{name:"Joan Lao",src:"/images/logos/blanco/joan-lao-blanco.svg"},{name:"LEGO",src:"/images/logos/blanco/lego-blanco.svg"},{name:"M Gallery",src:"/images/logos/blanco/m-gallery-blanco.svg"},{name:"Marriott",src:"/images/logos/blanco/marriott-blanco.svg"},{name:"Modus Operandi",src:"/images/logos/blanco/modus-operandi-blanco.svg"},
  ]},
  methodology: {
    headline: "Nuestra experiencia diseña la metodología",
    intro: "Ser una ayuda real para quien cuenta con nosotros es el motivo que nos ha guiado durante años para perfeccionar la forma en la que trabajamos.",
    subtitle: "Estos tres fundamentos dirigen cómo latroupe hace las cosas:",
    pillars: [
      { number:"I)", title:"Nuestro sistema se adapta al proyecto", subtitle:"(no al revés)", paragraphs:["Sabemos que un sistema de trabajo bien construido influye en la capacidad del equipo y en la calidad del resultado.","Por eso podemos resolver con autonomía y anticiparnos a los problemas sin supervisión constante, siempre desde la flexibilidad para integrarnos en las dinámicas internas sin complicarlas."] },
      { number:"II)", title:"Un modelo híbrido", subtitle:"(y de talento global)", paragraphs:["La experiencia acumulada en cada una de las áreas del sector nos permite identificar las necesidades concretas de cada situación y tener siempre disponible el talento específico para los requisitos del proyecto."] },
      { number:"III)", title:"Solucionamos", subtitle:"(con intención)", paragraphs:["Siendo conscientes de nuestro papel, proporcionamos algo más que ayuda extra.","En latroupe, aportamos valor adicional con propuestas, desde la experiencia, para enriquecer desde dentro."] },
    ],
  },
  whyUs: {
    headline: "¿Por qué nosotros?",
    paragraphs: [
      "En latroupe hemos estado en diferentes roles dentro de la construcción, la arquitectura y el diseño, la tecnología o la gestión empresarial.",
      "Por eso podemos ofrecer un servicio totalmente moldeable a las necesidades que tengas ahora mismo y que irá evolucionando a medida que estas también lo hagan.",
      "Nuestra forma de trabajar es sencilla (que no simple) y se basa en establecer relaciones sostenibles en el tiempo.",
      "Si crees que podemos ayudarte, todo empieza con una videollamada para conocernos.",
    ],
  },
  contact: {
    headline: "Empecemos un proyecto juntos",
    fields: { name:"Nombre", email:"Correo electrónico", company:"Mensaje", message:"Escríbenos tu mensaje", submit:"Enviar", sending:"Enviando...", sent:"¡Enviado!", error:"No se pudo enviar. Inténtalo de nuevo." },
    legal: "Al hacer clic en Enviar, aceptas nuestra política de protección de datos y que podamos ponernos en contacto contigo.",
    legalLinkPhrase: "política de protección de datos",
    legalLinkHref: "/es/aviso-legal",
  },
  footer: {
    links: [{label:"Privacidad",href:"/es/privacidad"},{label:"Cookies",href:"/es/cookies"},{label:"Aviso legal",href:"/es/aviso-legal"}],
    social: [{label:"Linkedin",href:"https://www.linkedin.com/company/latroupestudio/"},{label:"Instagram",href:"https://www.instagram.com/latroupestudio"},{label:"Pinterest",href:"https://www.pinterest.es/latroupestudio/"}],
    workWithUs: { label: "Trabaja con nosotros", href: "https://invented-cactus-ce6.notion.site/Trabajar-en-LaTroupe-cd9c990923954418bd2e6a3df58b2500" },
    copyright: "Desarrollado por latroupe ( ) 2026 ©",
    legal: "",
  },
  cookieBanner: {
    message: "Utilizamos cookies propias y de terceros para analizar el uso del sitio y mejorar nuestros servicios. Las cookies no esenciales solo se instalan con tu consentimiento.",
    moreInfo: "Más información",
    accept: "Aceptar",
    reject: "Rechazar",
  },
  overlay: { close:"CERRAR", inDevelopment:"En desarrollo", comingSoon:"Próximamente" },
  bim: {
    meta: {
      title: "BIM Consulting & Modelling Services UK | latroupe()",
      description: "BIM consulting, modelling and management services across the UK. ISO 19650 & COBie-ready, delivered to your standards and your timeline. Book a consultation.",
    },
    nav: {
      links: [{ label: "services", id: "services" }, { label: "case study", id: "case-study" }],
      contact: { label: "let's talk", id: "contacto" },
      home: { label: "latroupe", id: "/es" },
    },
    hero: {
      h1: "BIM Consulting & Modelling Services",
      subhead: "Coordinated, data-rich BIM — delivered to your standards, and to your timeline. We plug into your team at any project stage and keep you in control of your information from day one.",
      cta: { label: "book a consultation", id: "contacto" },
      ctaSub: "Tell us about your project, we'll reply within one working day.",
    },
    trustBand: {
      eyebrow: "trusted by leading studios and brands",
      tagline: "BIM delivered across the UK, Europe and beyond — for studios, contractors and developers.",
    },
    services: {
      eyebrow: "our bim services",
      headline: "End-to-end BIM services",
      sub: "Pick the ones you need, or let us run the lot.",
      items: [
        { number:"I)", title:"BIM Modelling", subtitle:"(revit)", paragraphs:["Accurate, data-rich Revit models built to your required level of detail (LOD 200–500). Architectural, structural and MEP BIM services, fully coordinated and ready for delivery."] },
        { number:"II)", title:"BIM Content Creation", subtitle:"(families & templates)", paragraphs:["Custom Revit families, templates and standards libraries — so your models stay consistent and reusable across every project."] },
        { number:"III)", title:"BIM Management & Information Management", subtitle:"(information delivery)", paragraphs:["A dedicated BIM manager to lead your information delivery — setting up the CDE, naming, and standards so your data stays clean, ordered and auditable."] },
        { number:"IV)", title:"BIM Execution Plan", subtitle:"(bep)", paragraphs:["We write and maintain your BIM Execution Plan so the whole team works to one agreed method — aligned with the UK BIM Framework from the start."] },
        { number:"V)", title:"BIM Coordination & Clash Detection", subtitle:"(multidisciplinary)", paragraphs:["Multidiscipline coordination that catches clashes before they reach site."] },
        { number:"VI)", title:"Embedded BIM Support", subtitle:"(your team, extended)", paragraphs:["Senior BIM consultants and Revit specialists who work as part of your studio for the length of a project — a true extension of your team, not a faceless production line."] },
        { number:"VII)", title:"BIM Project & Data Management Consultancy", subtitle:"(data & digital twin)", paragraphs:["From BIM project management consultancy to BIM data management consultancy and digital twin foundations — we keep the information layer of your project under control."] },
      ],
    },
    deliverables: {
      eyebrow: "what you get",
      headline: "Clear deliverables, agreed up front",
      sub: "You always know exactly what lands.",
      items: [
        { number:"01", title:"Coordinated Revit models", text:"to your chosen LOD (200 / 300 / 400 / 500)" },
        { number:"02", title:"Construction & GA drawings", text:"plans, sections, schematics and risers" },
        { number:"03", title:"Clash & coordination reports", text:"issues found, tracked and resolved" },
        { number:"04", title:"BOQ / quantities", text:"schedules pulled straight from the model" },
        { number:"05", title:"COBie data drops", text:"structured asset data for handover, aligned to your BEP" },
        { number:"06", title:"QA reports", text:"every model checked before it reaches you" },
      ],
    },
    adapts: {
      headline: "We adapt to you",
      sub: "Most providers make you fit their process. We do the opposite.",
      items: [
        { title:"We work in your hours.", text:"Real overlap with your working day — not a model that lands in your inbox overnight with no one to ask." },
        { title:"We join your team.", text:"We plug into your CDE, your naming, your workflow. You don't change how you work; we adapt to it." },
        { title:"We start from whatever you have.", text:"2D PDFs, CAD, an existing Revit model, markups or specs — we work from your inputs, in your formats." },
        { title:"You stay in control of your information.", text:"At every stage you can see exactly what's modelled, what's pending and where the data lives. No black boxes." },
      ],
    },
    riba: {
      eyebrow: "support at any riba stage",
      headline: "Whatever stage your project is at, we plug in.",
      caption: "Come to us at the start or pick us up mid-project — from BEP and standards, through modelling and coordination, to COBie-ready handover.",
      stages: [
        { number:"0", label:"Strategic Definition" },
        { number:"1", label:"Preparation & Briefing" },
        { number:"2", label:"Concept Design" },
        { number:"3", label:"Spatial Coordination" },
        { number:"4", label:"Technical Design" },
        { number:"5", label:"Manufacturing & Construction" },
        { number:"6", label:"Handover" },
        { number:"7", label:"Use" },
      ],
    },
    standards: {
      eyebrow: "standards & quality, in plain terms",
      headline: "Compliance shouldn't feel like an exam.",
      sub: "We handle the standards so you don't have to memorise them.",
      items: [
        { code:"ISO 19650", description:"The international standard for managing information across a project's life cycle." },
        { code:"COBie", description:"Structured asset data your client can actually use after handover." },
        { code:"UK BIM Framework / PAS 1192", description:"The UK way of working, built into how we run every job." },
      ],
    },
    sectors: {
      eyebrow: "sectors we work in",
      headline: "Generalist by design. We deliver BIM across:",
      items: ["Residential","Commercial & offices","Hospitality","Retail","Mixed-use","Education","Airports & aviation","Data centres","Interiors & fit-out"],
      sub: "If it gets designed, built and operated, we can model and manage it.",
    },
    why: {
      eyebrow: "why latroupe()",
      headline: "Clarity and control — from the first model to handover.",
      items: [
        { title:"Clarity and control.", text:"You always know what's done, what's next and where your data is." },
        { title:"We adapt to your team.", text:"Your hours, your workflow, your standards." },
        { title:"Multi-standard, not single-track.", text:"ISO 19650, COBie and the UK BIM Framework are day-to-day for us, not a learning curve." },
      ],
    },
    tools: {
      eyebrow: "built in-house",
      headline: "We build our own tools",
      sub: "We don't just deliver models — we build software to keep BIM data clean and ordered. It's how we guarantee the rigour behind every project we hand over.",
      items: [
        { name:"specto", description:"model & data inspection", img:"/images/bim-consultancy/tools/specto.png" },
        { name:"modelcleaner", description:"clean, ordered bim data", img:"/images/bim-consultancy/tools/modelcleaner.png" },
        { name:"pdf comparator", description:"drawing revision compare", img:"/images/bim-consultancy/tools/pdfcomparator.svg" },
      ],
    },
    caseStudy: {
      eyebrow: "case study",
      headline: "LEGO London Hub",
      heroImage: "/images/case-studies/lego-london-hub/hero.jpg",
      location: "London, UK",
      year: "2026",
      area: "20,000 sqm",
      typology: "Workplace",
      author: "BDG architecture + design",
      endClient: "LEGO",
      intro: "latroupe() joined BDG at Stage 2 as its BIM management and production partner for the LEGO London Hub fit-out. We set up and ran the project's entire BIM information environment and then delivered the Stage 3 model and full drawing package — all inside BDG's secured platforms. The challenge was to stand up a fully ISO 19650-compliant information environment from scratch, align to BDG's in-house BIM 7AA standard, coordinate multiple parties and consultants within a controlled corporate IT environment, and produce a large, multi-package Stage 3 drawing set at pace with full traceability.",
      standards: "ISO 19650 · BDG BIM 7AA standard · CDE (Dalux + Autodesk Construction Cloud) · IFC exchange · RIBA Plan of Work 2020 · UK Building Regulations",
      whatWeDid: [
        { title:"BIM & information management", items:[
          "Authored and maintained the BIM Execution Plan (including a Revit-to-Dalux guide), reviewed the EIR and produced the MIDP, BDG TIDP, Information Responsibility Matrix and risk register.",
          "Set up the CDE end-to-end: Dalux setup and plug-ins, model structure diagram, levels & grids model, model-splitting strategy, IFC export/upload and ACC access & permissions management.",
          "Ran BIM coordination meetings, clash-detection tests and successive model uploads (Dalux v01–v04 and Stage 3+), plus BDG model reviews and audits (worksets, FF&E splash page, catering model to BDG ACC).",
          "Wrote the BIM text and appendices for the Stage 3 report.",
        ]},
        { title:"BIM modelling & drawing production", items:[
          "Planning & existing plans",
          "Proposed GA; partitions (AV back-to-back meeting rooms, teapoint bulkheads, conference-room walls); raised-access-floor plans; floor finishes",
          "Elevations; proposed sections",
          "Joinery, stairs / working platform",
          "Detail drawings",
          "Doors and fire strategy; AV modelling",
        ]},
      ],
      result: "A fully governed, ISO 19650-compliant BIM environment and a comprehensive, coordinated Stage 3 model and drawing set — delivered continuously inside BDG's platforms and standards, with latroupe() acting as BDG's embedded BIM management and production team.",
      imageCredit: "Image © LEGO",
    },
    faq: {
      eyebrow: "faq",
      headline: "FAQs",
      items: [
        { question:"Can you join a project that's already underway?", answer:"Yes. We regularly pick projects up mid-stage — we audit what already exists, set up or clean the information environment, and carry on from there without disrupting your delivery." },
        { question:"How do we get started?", answer:"A short call to understand the project and its stage. We then propose the scope, standards and deliverables — and agree them — before the collaboration begins." },
        { question:"Fixed fee or by stage?", answer:"Both. We scope by stage or by deliverable, and agree the commercial model that fits how you run the project." },
        { question:"Can you provide extra BIM capacity for our team?", answer:"Yes. We can embed senior BIM consultants and Revit specialists in your studio for the length of a project, working as part of your team." },
        { question:"Can you work inside our own platforms and standards?", answer:"Yes. We routinely deliver entirely inside our clients' secured platforms and to their in-house BIM standards, working as part of their environment rather than imposing ours." },
        { question:"What is a BIM Execution Plan (BEP)?", answer:"A document that sets out how BIM will be delivered on your project — roles, standards, software, LOD and data drops — so the whole team works one way. We write and maintain it for you." },
        { question:"What does a BIM manager do?", answer:"A BIM manager leads your information delivery — setting standards, running the CDE and keeping data quality high across every discipline. We can provide one for your project." },
        { question:"Which software do you use?", answer:"Revit is our main modelling platform, but we also work in ArchiCAD and with tools like Dalux and other common BIM platforms. If you have a specific requirement, tell us — chances are we can help." },
        { question:"Do you deliver COBie and structured asset data?", answer:"Yes. We hand over COBie-ready, structured data your client can actually use to operate the building after handover." },
      ],
    },
    header: {
      popup: {
        whoLabel: "( who are you? )",
        namePlaceholder: "Your name",
        reachLabel: "( how do we reach you? )",
        emailPlaceholder: "Your email",
        projectLabel: "( what's the project? )",
        projectPlaceholder: "Type, stage, location",
        moreLabel: "( tell us more )",
        morePlaceholder: "A short description of what you need",
        submit: "Send",
        legal: "By submitting this form you agree to our privacy policy.",
        legalLinkPhrase: "privacy policy",
        legalLinkHref: "/es/privacidad",
        closeAriaLabel: "Close",
      },
    },
    ctaSection: {
      headline: "Let's talk.",
      sub: "Tell us where your project is — start, mid-stage or already on site. We'll map the BIM support you need, to your standards and your timeline. No obligation, and we reply within one working day.",
      fields: {
        whoLabel: "( who are you? )",
        namePlaceholder: "Your name",
        reachLabel: "( how do we reach you? )",
        emailPlaceholder: "Your email",
        projectLabel: "( what's the project? )",
        projectPlaceholder: "Type, stage, location",
        moreLabel: "( tell us more )",
        morePlaceholder: "A short description of what you need",
        submit: "Send",
        sending: "Sending...",
        sent: "Sent!",
        error: "Could not send. Please try again.",
      },
      legal: "By submitting this form you agree to our privacy policy. We only use your details to reply to your enquiry — never for anything else.",
      legalLinkPhrase: "privacy policy",
      legalLinkHref: "/es/privacidad",
    },
  },
};
export default es;
